# Generated by Django 4.2 on 2023-09-15 09:05

from django.db import migrations, models

import documents.models
import supervision.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_value_here', max_length=255)),
                ('files', models.FileField(upload_to=documents.models.upload_to_checklist)),
                ('comment', models.BooleanField()),
            ],
        ),
    ]
