# Generated by Django 4.2 on 2023-09-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0003_controlcard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcard',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
