# Generated by Django 4.2 on 2023-09-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_check_area'),
        ('supervision', '0004_alter_controlcard_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.companies')),
            ],
        ),
        migrations.AddField(
            model_name='controlcard',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='supervision.checkarea'),
            preserve_default=False,
        ),
    ]
