# Generated by Django 4.2 on 2023-09-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0005_checkarea_controlcard_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkarea',
            name='company',
        ),
    ]
