# Generated by Django 4.2 on 2023-09-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_check_area'),
        ('supervision', '0006_remove_checkarea_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcard',
            name='area',
        ),
        migrations.AddField(
            model_name='checkarea',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.companies'),
            preserve_default=False,
        ),
    ]
