# Generated by Django 4.2 on 2023-09-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0008_controlcard_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkarea',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
