# Generated by Django 4.2 on 2023-09-16 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0009_alter_checkarea_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcard',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supervision.checkarea'),
        ),
        migrations.AlterField(
            model_name='controlcard',
            name='name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
