# Generated by Django 4.2 on 2023-09-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_check_area'),
        ('supervision', '0010_alter_controlcard_area_alter_controlcard_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCheck', models.BooleanField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.checkarea')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.companies')),
            ],
        ),
    ]
