# Generated by Django 4.2 on 2023-09-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0013_checkmonth_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkmonth',
            name='company',
        ),
        migrations.AddField(
            model_name='checkmonth',
            name='month',
            field=models.IntegerField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
