# Generated by Django 4.2 on 2023-09-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0014_remove_checkmonth_company_checkmonth_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmonth',
            name='month',
            field=models.IntegerField(),
        ),
    ]
