# Generated by Django 4.2 on 2023-09-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0015_alter_checkmonth_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcard',
            name='name',
        ),
        migrations.AddField(
            model_name='controlcard',
            name='month',
            field=models.IntegerField(default=1, max_length=255),
        ),
    ]
