# Generated by Django 4.2 on 2023-09-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0017_alter_controlcard_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcard',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.checkarea'),
        ),
    ]
