# Generated by Django 4.2 on 2023-09-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0019_alter_controlcard_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkmonth',
            old_name='isCheck',
            new_name='checking',
        ),
    ]
