# Generated by Django 4.2 on 2023-09-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0020_rename_ischeck_checkmonth_checking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkarea',
            options={'verbose_name': 'Область проверки', 'verbose_name_plural': 'Область проверков'},
        ),
        migrations.AlterModelOptions(
            name='checkmonth',
            options={'verbose_name': 'Проверочный месяц', 'verbose_name_plural': 'Проверочные месяца'},
        ),
        migrations.AlterModelOptions(
            name='controlcard',
            options={'verbose_name': 'Контрольная карта', 'verbose_name_plural': 'Контрольные карты'},
        ),
        migrations.AlterField(
            model_name='controlcard',
            name='area',
            field=models.ForeignKey(default=119, on_delete=django.db.models.deletion.CASCADE, to='supervision.checkarea'),
        ),
    ]
