# Generated by Django 4.2 on 2023-09-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0021_alter_checkarea_options_alter_checkmonth_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkarea',
            options={'verbose_name': 'Область проверки', 'verbose_name_plural': 'Области проверков'},
        ),
    ]
