# Generated by Django 4.2 on 2023-09-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0022_alter_checkarea_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcard',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supervision.checkarea'),
        ),
    ]
