# Generated by Django 4.2 on 2023-09-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0023_alter_controlcard_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControlCard',
            new_name='Checklist',
        ),
    ]
