# Generated by Django 4.2 on 2023-09-21 15:27

from django.db import migrations, models
import django.db.models.deletion

import documents.models
import supervision.models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0024_rename_controlcard_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.FileField(upload_to=documents.models.upload_to_letter_to_avia)),
                ('fine_protocol', models.FileField(upload_to=documents.models.upload_to_fine_protocol)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist')),
            ],
        ),
    ]
