# Generated by Django 4.2 on 2023-09-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0025_prescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Предписание', 'verbose_name_plural': 'Предписания'},
        ),
    ]
