# Generated by Django 4.2 on 2023-09-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0026_alter_prescription_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
