# Generated by Django 4.2 on 2023-09-25 16:55

from django.db import migrations, models
import django.db.models.deletion

import documents.models
import supervision.models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0027_checklist_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to=documents.models.upload_to_report)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='PKD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.FileField(upload_to=documents.models.upload_to_letter_from_avia)),
                ('pkd', models.FileField(upload_to=documents.models.upload_to_pkd)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.FileField(upload_to=documents.models.upload_to_notification)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Elimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.FileField(upload_to=documents.models.upload_to_elimination)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.FileField(upload_to=documents.models.upload_to_approval)),
                ('deadline', models.DateField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist')),
            ],
        ),
    ]
