# Generated by Django 4.2 on 2023-09-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0028_report_pkd_notification_elimination_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'verbose_name': 'Одобрение', 'verbose_name_plural': 'Одобрения'},
        ),
        migrations.AlterModelOptions(
            name='pkd',
            options={'verbose_name': 'ПКД', 'verbose_name_plural': 'ПКД'},
        ),
        migrations.AddField(
            model_name='checklist',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.checklist'),
        ),
    ]
