# Generated by Django 4.2 on 2023-09-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0031_alter_checklist_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist'),
        ),
        migrations.AlterField(
            model_name='elimination',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist'),
        ),
        migrations.AlterField(
            model_name='pkd',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist'),
        ),
        migrations.AlterField(
            model_name='report',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checklist'),
        ),
    ]
