# Generated by Django 4.2 on 2023-09-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0033_checkarea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checkmonth'),
        ),
    ]
