# Generated by Django 4.2 on 2023-09-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0034_alter_checklist_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkarea',
            name='user',
        ),
    ]
