# Generated by Django 4.2 on 2023-10-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0038_alter_permission_area_alter_permission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
