# Generated by Django 4.2 on 2023-10-02 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0039_permission_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checkarea'),
        ),
    ]
