# Generated by Django 4.2 on 2023-10-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0040_alter_checklist_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('Checked', 'Проверено'), ('Checking', 'Проверяется'), ('NotChecked', 'Еще не проверено')], default='NotChecked', max_length=20),
        ),
    ]
