# Generated by Django 4.2 on 2023-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0042_remove_checklist_status_checkmonth_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmonth',
            name='status',
            field=models.CharField(choices=[('Checked', 'Проверено'), ('Checking', 'Проверяется'), ('NotChecked', 'Еще не проверено'), ('Moved', 'Проверка перенесена')], default='NotChecked', max_length=20),
        ),
    ]
