# Generated by Django 4.2 on 2023-10-06 07:46

from django.db import migrations, models
import django.db.models.deletion

import documents.models
import supervision.models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0043_alter_checkmonth_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raport', models.FileField(upload_to=documents.models.upload_to_moved)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.checkarea')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.checkmonth')),
            ],
            options={
                'verbose_name': 'Рапорт',
                'verbose_name_plural': 'Рапорты',
            },
        ),
    ]
