# Generated by Django 4.2 on 2023-10-16 08:43

from django.db import migrations, models

import documents.models
import supervision.models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0045_alter_moved_area_alter_moved_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='fine_protocol',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.upload_to_fine_protocol),
        ),
    ]
