# Generated by Django 4.2 on 2023-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0046_alter_prescription_fine_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkmonth',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
