# Generated by Django 4.2 on 2023-10-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0047_checkmonth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='area',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='month',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='original',
        ),
        migrations.RemoveField(
            model_name='elimination',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='moved',
            name='area',
        ),
        migrations.RemoveField(
            model_name='moved',
            name='month',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='pkd',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='report',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='Elimination',
        ),
        migrations.DeleteModel(
            name='Moved',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PKD',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
