# Generated by Django 4.2 on 2023-10-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_company_address_alter_company_code_and_more'),
        ('supervision', '0049_remove_checklist_area_remove_checklist_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OversightPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.company')),
            ],
            options={
                'verbose_name': 'Период надзора',
                'verbose_name_plural': 'Периоды надзора',
            },
        ),
    ]
