# Generated by Django 4.2 on 2023-10-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0050_oversightperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='oversightperiod',
            name='period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
