# Generated by Django 4.2 on 2023-10-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0052_remove_checkmonth_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkarea',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supervision.oversightperiod'),
            preserve_default=False,
        ),
    ]
