# Generated by Django 4.2 on 2023-10-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0053_checkarea_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oversightperiod',
            name='period',
            field=models.CharField(max_length=255),
        ),
    ]
