# Generated by Django 4.2 on 2023-10-20 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervision', '0054_alter_oversightperiod_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until_the_deadline', models.IntegerField()),
                ('email_sent', models.BooleanField(default=False)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.checkmonth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
