# Generated by Django 4.2.7 on 2023-11-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supervision", "0057_rename_email_sent_deadline_first_email_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deadline",
            name="last_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
