# Generated by Django 4.2 on 2023-10-16 16:04

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervision', '0049_remove_checklist_area_remove_checklist_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('files', models.FileField(upload_to=documents.models.upload_to_checklist, verbose_name='Контрольная карта')),
                ('comment', models.BooleanField()),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checkarea')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checkmonth')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.checklist')),
            ],
            options={
                'verbose_name': 'Контрольная карта',
                'verbose_name_plural': 'Контрольные карты',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to=documents.models.upload_to_report)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.FileField(upload_to=documents.models.upload_to_letter_to_avia)),
                ('fine_protocol', models.FileField(blank=True, null=True, upload_to=documents.models.upload_to_fine_protocol)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.checklist')),
            ],
            options={
                'verbose_name': 'Предписание',
                'verbose_name_plural': 'Предписания',
            },
        ),
        migrations.CreateModel(
            name='PKD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.FileField(upload_to=documents.models.upload_to_letter_from_avia)),
                ('pkd', models.FileField(upload_to=documents.models.upload_to_pkd)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.checklist')),
            ],
            options={
                'verbose_name': 'ПКД',
                'verbose_name_plural': 'ПКД',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.FileField(upload_to=documents.models.upload_to_notification)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Moved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raport', models.FileField(upload_to=documents.models.upload_to_moved)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checkarea')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.checkmonth')),
            ],
            options={
                'verbose_name': 'Рапорт',
                'verbose_name_plural': 'Рапорты',
            },
        ),
        migrations.CreateModel(
            name='Elimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.FileField(upload_to=documents.models.upload_to_elimination)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.FileField(upload_to=documents.models.upload_to_approval)),
                ('deadline', models.DateField()),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.checklist')),
            ],
            options={
                'verbose_name': 'Одобрение',
                'verbose_name_plural': 'Одобрения',
            },
        ),
    ]
