# Generated by Django 4.2.3 on 2023-08-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind_of_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kind of activity',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('number', models.IntegerField()),
                ('code', models.CharField(max_length=6, unique=True)),
                ('validity', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=256, unique=True)),
                ('first_phone', models.CharField(default='SOME NUMBER', max_length=20, unique=True)),
                ('second_phone', models.CharField(default='SOME NUMBER', max_length=20, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('kind_of_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.kind_of_activity')),
            ],
        ),
    ]
