# Generated by Django 4.2.3 on 2023-08-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='products/')),
            ],
        ),
        migrations.AlterField(
            model_name='companies',
            name='first_phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='second_phone',
            field=models.CharField(blank=True, default=' ', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('point', models.ManyToManyField(related_name='regions', to='products.companies')),
                ('report', models.ManyToManyField(related_name='regions', to='products.report')),
            ],
        ),
    ]
