# Generated by Django 4.2.3 on 2023-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_report_pdf_file_alter_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(upload_to='products/templates/reports/'),
        ),
    ]
