# Generated by Django 4.2.3 on 2023-09-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_report_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(upload_to='../products/templates/reports/'),
        ),
    ]
