# Generated by Django 4.2.3 on 2023-09-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_report_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='report',
        ),
        migrations.AddField(
            model_name='companies',
            name='report',
            field=models.ManyToManyField(related_name='regions', to='products.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(upload_to='reports/'),
        ),
    ]
