# Generated by Django 4.2.3 on 2023-09-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_region_report_companies_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='report',
        ),
        migrations.AddField(
            model_name='region',
            name='report',
            field=models.ManyToManyField(related_name='regions', to='products.report'),
        ),
    ]
