# Generated by Django 4.2.3 on 2023-09-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_companies_report_region_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='report',
        ),
        migrations.AddField(
            model_name='companies',
            name='report',
            field=models.ManyToManyField(related_name='companies', to='products.report'),
        ),
    ]
