# Generated by Django 4.2 on 2023-09-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_check_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_area',
            old_name='name',
            new_name='title',
        ),
    ]
