# Generated by Django 4.2 on 2023-09-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_name_check_area_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check_area',
        ),
    ]
