# Generated by Django 4.2 on 2023-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_check_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='report',
        ),
        migrations.AddField(
            model_name='companies',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
