# Generated by Django 4.2 on 2023-09-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_companies_report_companies_slug_delete_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='slug',
        ),
    ]
