# Generated by Django 4.2 on 2023-09-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_companies_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kind_of_activity',
            new_name='KindOfActivity',
        ),
    ]
