# Generated by Django 4.2 on 2023-09-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_kind_of_activity_kindofactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
