# Generated by Django 4.2 on 2023-09-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_companies_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
