# Generated by Django 4.2 on 2023-09-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_company_options_alter_kindofactivity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindofactivity',
            options={'verbose_name': 'Вид деятельности', 'verbose_name_plural': 'Виды деятельности'},
        ),
    ]
