# Generated by Django 4.2 on 2023-10-16 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0025_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=256, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='3-буквен КОД ИКАО'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=64, unique=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='first_phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='1-номер телефона'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kind_of_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.kindofactivity', verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название авиакомпании/Управленческий персонал'),
        ),
        migrations.AlterField(
            model_name='company',
            name='number',
            field=models.IntegerField(verbose_name='Номер СЭ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='company',
            name='second_phone',
            field=models.CharField(blank=True, default=' ', max_length=20, unique=True, verbose_name='2-номер телефона'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус СЭ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Как пользователь'),
        ),
        migrations.AlterField(
            model_name='company',
            name='validity',
            field=models.DateField(verbose_name='Срок действия сертификата эксплуатанта (СЭ)'),
        ),
    ]
